//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAspNet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libros
    {
        [Display(Name = "#")]
        public int idLibro { get; set; }
        [Display(Name = "Nombre del libro")]
        public string nombreLibro { get; set; }
        [Display(Name = "Autor")]
        public string autor { get; set; }
    }
}
