//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAspNet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Prestamos
    {
        [Display(Name = "#")]
        public int idPrestamo { get; set; }


        [Display(Name = "idLibro")]
        public int idLibro { get; set; }


        [Display(Name = "Fecha de prestamo")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime fechaPrestamo { get; set; }



        [Display(Name = "Fecha de devolucion")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> fechaDevolucion { get; set; }


        [Display(Name = "Usuario")]
        public string nombreUsuario { get; set; }
    
        public virtual Libros Libros { get; set; }
    }
}
